# Generated by Django 5.2.3 on 2025-06-17 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 13, 34, 59, 999338), verbose_name='Upload Date'),
        ),
    ]
