# Generated by Django 5.2.3 on 2025-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_semester_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Teacher Email'),
        ),
    ]
